[default]
Speed=450.0
JumpVelocity=-600.0
Health=100.0
Damage=10.0
BlockHealth=3.0
BlockCooldown=3.0
CanDoubleJump=true

; Animations may need bounding box size changes.
; 'default' should match the size defined in Godot.
[boundingbox]
default=Vector2(80.0, 156)
attack_1=Vector2(165,156)
attack_2=Vector2(175,156)

; Animations may need offsets for bounding box size changes.
; 'default' should match the transform size defined in Godot.
; 'flipH' is a speical keyword. It will shift the resulting bounding box after animation offsets
; if a FlipH invert occurs during that animation
; animations may also have different offsets when flipped, so please add '_flipH' to handle such cases
[boundingboxoffsets]
default=Vector2(-1, 72.0)
flipH=Vector2(-10, 0.0)
attack_1=Vector2(50, 72.0)
attack_1_flipH=Vector2(-50, 72.0)
attack_2=Vector2(60, 72.0)
attack_2_flipH=Vector2(-60, 72.0)