[default]
Speed=450.0
JumpVelocity=-600.0
CanDoubleJump=true

; Animations may need bounding box size changes.
; 'default' should match the size defined in Godot.
[boundingbox]
default=Vector2(83, 173)
attack_1=Vector2(340,173)
attack_2=Vector2(340,173)

; Animations may need offsets for bounding box size changes.
; 'default' should match the transform size defined in Godot.
; 'flipH' is a speical keyword. It will shift the resulting bounding box after animation offsets
; if a FlipH invert occurs during that animation
; animations may also have different offsets when flipped, so please add '_flipH' to handle such cases
[boundingboxoffsets]
default=Vector2(-25.5, 110.5)
flipH=Vector2(51.0, 0.0)
attack_1=Vector2(100, 110.5)
attack_1_flipH=Vector2(-100, 110.5)
attack_2=Vector2(80, 110.5)
attack_2_flipH=Vector2(-80, 110.5)